# Generated by Django 3.1.2 on 2021-06-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('url', models.TextField(verbose_name='URL')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='data.category', verbose_name='関連カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL')),
                ('html', models.TextField(verbose_name='HTML')),
                ('check', models.CharField(choices=[('ok', 'ok'), ('no', 'no')], max_length=10, verbose_name='振り分け判定')),
            ],
            options={
                'verbose_name': 'データ',
                'verbose_name_plural': 'データ',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='医師名')),
                ('title', models.CharField(max_length=250, verbose_name='肩書き')),
                ('profile', models.TextField(verbose_name='プロフィール')),
                ('image', models.ImageField(upload_to='images/', verbose_name='医師画像URL')),
                ('url', models.TextField(verbose_name='URL')),
            ],
            options={
                'verbose_name': '医師情報',
                'verbose_name_plural': '医師情報',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='グループ名')),
                ('url', models.TextField(verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.category', verbose_name='関連カテゴリ')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='病院名')),
                ('url', models.TextField(verbose_name='URL')),
            ],
            options={
                'verbose_name': '病院名',
                'verbose_name_plural': '病院名',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ページタイトル')),
                ('html', models.TextField(verbose_name='HTML')),
                ('url', models.TextField(verbose_name='URL')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.category', verbose_name='関連カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='data.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'ページ',
                'verbose_name_plural': 'ページ',
            },
        ),
        migrations.CreateModel(
            name='OutpatientDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.CharField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日')], max_length=10, verbose_name='曜日')),
                ('am_pm', models.CharField(choices=[(1, '午前'), (2, '午後')], max_length=10, verbose_name='午前・午後')),
                ('other', models.TextField(verbose_name='補足')),
                ('url', models.TextField(verbose_name='URL')),
                ('doctor', models.ManyToManyField(to='data.Doctor', verbose_name='医師名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group', verbose_name='関連グループ')),
                ('tag', models.ManyToManyField(to='data.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '外来担当医師',
                'verbose_name_plural': '外来担当医師',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.page', verbose_name='ページ'),
        ),
        migrations.AddField(
            model_name='group',
            name='tag',
            field=models.ManyToManyField(blank=True, to='data.Tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('html', models.TextField(verbose_name='内容')),
                ('url', models.TextField(verbose_name='URL')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group', verbose_name='関連グループ名')),
                ('tag', models.ManyToManyField(to='data.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '要素',
                'verbose_name_plural': '要素',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group', verbose_name='関連グループ名'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tag',
            field=models.ManyToManyField(to='data.Tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='DepartmentTimeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(choices=[('受付', 1), ('診療', 2)], max_length=10, verbose_name='受付・診療選択')),
                ('start_time', models.TimeField(default=0, verbose_name='開始時間')),
                ('end_time', models.TimeField(default=0, verbose_name='終了時間')),
                ('type', models.CharField(choices=[('初診', 1), ('再診', 2)], max_length=10, verbose_name='初診・再診')),
                ('url', models.TextField(verbose_name='URL')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group', verbose_name='関連グループ')),
                ('tag', models.ManyToManyField(to='data.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '受付・診療時間',
                'verbose_name_plural': '受付・診療時間',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.hospital', verbose_name='関連病院名'),
        ),
    ]
